on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v1

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          outFile: './output/test.json'

      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "Latest tag: ${{ steps.hello.outputs.latest_release }}";
          echo "Release data: ${{ steps.hello.outputs.data_json }}";
          ls -la output
